[theme]
# Primary accent for interactive elements
primaryColor = '#4b2e83'

# Background color for the main content area
backgroundColor = 'white'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#e0ded7'

# Color used for almost all text
textColor = '#23221f'

# Font family for all text in the zebra, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
